name:                coqtop-elaborate
version:             0.1.0.0
github:              "Krantz-XRF/coqtop-elaborate"
license:             BSD3
author:              "Xie Ruifeng"
maintainer:          "krantz.xrf@outlook.com"
copyright:           "AGPL-3.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Krantz-XRF/coqtop-elaborate#readme>

dependencies:
- base >= 4.7 && < 5
- process

default-extensions:
# Type level goodies
- ConstraintKinds
- DataKinds
- TypeOperators
- RankNTypes
# Deriving
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveLift
- DeriveAnyClass
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
# Flexible type classes
- FlexibleContexts
- FlexibleInstances
- QuantifiedConstraints
- MultiParamTypeClasses
- FunctionalDependencies
# Type applications
- TypeApplications
- ScopedTypeVariables
# Pattern synonyms
- PatternSynonyms
# Grammar candies
- ViewPatterns
- LambdaCase
- TupleSections
- BangPatterns
- RecordWildCards
- BlockArguments

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  coqtop-elaborate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - coqtop-elaborate

tests:
  coqtop-elaborate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - coqtop-elaborate
